/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/planner/configurations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Configurations */
        get: operations["configurations_api_v1_planner_configurations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/planner/configurations/{configuration_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Configuration Detail */
        get: operations["configuration_detail_api_v1_planner_configurations__configuration_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/planner/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Planner Options */
        get: operations["planner_options_api_v1_planner_options_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ConfidenceLevel
         * @enum {string}
         */
        ConfidenceLevel: "low" | "medium" | "high";
        /** ConfidenceResponse */
        ConfidenceResponse: {
            level: components["schemas"]["ConfidenceLevel"];
            /** Reason */
            reason: string;
        };
        /** DemandRangeResponse */
        DemandRangeResponse: {
            /** Base Units */
            base_units: number;
            /** Downside Units */
            downside_units: number;
            /** Upside Units */
            upside_units: number;
        };
        /** EquipmentResponse */
        EquipmentResponse: {
            /** Acoustic */
            acoustic: boolean | null;
            /** Camera Adas */
            camera_adas: boolean | null;
            /** Heated */
            heated: boolean | null;
            /** Hud */
            hud: boolean | null;
            /** Rain Light Sensor */
            rain_light_sensor: boolean | null;
        };
        /**
         * EvidenceStatus
         * @enum {string}
         */
        EvidenceStatus: "demonstration" | "prototype" | "validated";
        /** FieldError */
        FieldError: {
            /** Field */
            field: string;
            /** Message */
            message: string;
        };
        /** HealthResponse */
        HealthResponse: {
            /** Data Version */
            data_version: string;
            /** Fixture Ready */
            fixture_ready: boolean;
            /** Status */
            status: string;
        };
        /** PlannerOptionsResponse */
        PlannerOptionsResponse: {
            /** Brands */
            brands: string[];
            /** Evidence Statuses */
            evidence_statuses: components["schemas"]["EvidenceStatus"][];
            /** Horizons */
            horizons: number[];
            /** Markets */
            markets: string[];
            /** Models */
            models: string[];
            scenario: components["schemas"]["ScenarioResponse"];
        };
        /** PlannerPageResponse */
        PlannerPageResponse: {
            /** Items */
            items: components["schemas"]["PlanningConfigurationResponse"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Pages */
            pages: number;
            summary: components["schemas"]["PlannerSummaryResponse"];
            /** Total */
            total: number;
        };
        /** PlannerSummaryResponse */
        PlannerSummaryResponse: {
            /** Base Units */
            base_units: number;
            /** Candidate Count */
            candidate_count: number;
            /** Downside Units */
            downside_units: number;
            /** Upside Units */
            upside_units: number;
        };
        /** PlanningConfigurationResponse */
        PlanningConfigurationResponse: {
            /** Body Style */
            body_style: string;
            /** Brand */
            brand: string;
            /** Configuration Id */
            configuration_id: string;
            data_quality_confidence: components["schemas"]["ConfidenceResponse"];
            /** Data Version */
            data_version: string;
            demand: components["schemas"]["DemandRangeResponse"];
            /** Drive Side */
            drive_side: string | null;
            equipment: components["schemas"]["EquipmentResponse"];
            evidence_status: components["schemas"]["EvidenceStatus"];
            /** Facelift */
            facelift: string | null;
            /** Forecast Horizon */
            forecast_horizon: number;
            /** Generation */
            generation: string;
            identity_confidence: components["schemas"]["ConfidenceResponse"];
            /** Market */
            market: string;
            /** Model */
            model: string;
            /** Model Year End */
            model_year_end: number;
            /** Model Year Start */
            model_year_start: number;
            /** Part Family */
            part_family: string | null;
            /** Replacement Rate */
            replacement_rate: number;
            /** Sku */
            sku: string | null;
            /** Sources */
            sources: components["schemas"]["SourceSummaryResponse"][];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Vehicle Exposure Units */
            vehicle_exposure_units: number;
        };
        /** ProblemResponse */
        ProblemResponse: {
            /** Code */
            code: string;
            /** Correlation Id */
            correlation_id: string;
            /** Field Errors */
            field_errors?: components["schemas"]["FieldError"][];
            /** Message */
            message: string;
        };
        /** ScenarioResponse */
        ScenarioResponse: {
            /** Data Version */
            data_version: string;
            /** Description */
            description: string;
            evidence_status: components["schemas"]["EvidenceStatus"];
            /** Name */
            name: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * SortDirection
         * @enum {string}
         */
        SortDirection: "asc" | "desc";
        /**
         * SortField
         * @enum {string}
         */
        SortField: "base_demand" | "downside_demand" | "upside_demand" | "brand" | "model" | "identity_confidence" | "data_quality_confidence";
        /** SourceSummaryResponse */
        SourceSummaryResponse: {
            /** Description */
            description: string;
            /** Name */
            name: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    configurations_api_v1_planner_configurations_get: {
        parameters: {
            query?: {
                market?: string[] | null;
                horizon?: number[] | null;
                brand?: string[] | null;
                model?: string[] | null;
                evidence?: components["schemas"]["EvidenceStatus"][] | null;
                sort?: components["schemas"]["SortField"];
                direction?: components["schemas"]["SortDirection"];
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlannerPageResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
        };
    };
    configuration_detail_api_v1_planner_configurations__configuration_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                configuration_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanningConfigurationResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
        };
    };
    planner_options_api_v1_planner_options_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlannerOptionsResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
        };
    };
}
