"""Application boundary for immutable evidence persistence."""

from __future__ import annotations

from collections.abc import Sequence
from typing import Protocol

from icor.domain.evidence import (
    CanonicalVehicle,
    IdentityMapping,
    Observation,
    PublishedValue,
    ReleaseManifest,
)
from icor.domain.snapshots import SnapshotManifest


class EvidenceRepository(Protocol):
    """Persist and query append-only evidence records."""

    def add_release(self, release: ReleaseManifest) -> None: ...

    def add_observations(self, observations: Sequence[Observation]) -> None: ...

    def add_vehicle(self, vehicle: CanonicalVehicle) -> None: ...

    def add_mapping(self, mapping: IdentityMapping) -> None: ...

    def add_published_values(self, values: Sequence[PublishedValue]) -> None: ...

    def add_snapshot(self, snapshot: SnapshotManifest) -> None: ...

    def get_release(self, release_id: str) -> ReleaseManifest | None: ...

    def get_observation(self, observation_id: str) -> Observation | None: ...

    def get_vehicle(self, vehicle_id: str) -> CanonicalVehicle | None: ...

    def get_mapping(self, mapping_id: str) -> IdentityMapping | None: ...

    def get_published_value(self, value_id: str) -> PublishedValue | None: ...

    def get_snapshot(self, snapshot_id: str) -> SnapshotManifest | None: ...

    def list_releases(self) -> tuple[ReleaseManifest, ...]: ...

    def list_observations(self) -> tuple[Observation, ...]: ...

    def list_vehicles(self) -> tuple[CanonicalVehicle, ...]: ...

    def list_mappings(self) -> tuple[IdentityMapping, ...]: ...

    def list_published_values(self) -> tuple[PublishedValue, ...]: ...

    def list_snapshots(self) -> tuple[SnapshotManifest, ...]: ...
