[theme]
primaryColor = "#2AA7C9"
backgroundColor = "#0D2B3E"
secondaryBackgroundColor = "#12344A"
textColor = "#EAF6FD"
font = "sans serif"

[server]
# Robust ignore: match “data” or “logs” anywhere in the full path
folderWatchBlacklist = [".*/data/.*", ".*/logs/.*"]
fileWatcherType = "none"
runOnSave = false
